### ISSUE TITLE
Lien vers documentation GitHub erroné (cours CI)

### ISSUE THREAD

**Issue by MarionPlt** [dduportal/esgi-courses#14]
Dans le document ci.adoc, section "Essayons GitHub Action",  le lien  [https://docs.github.com/en/free-pro-team@latest/actions/reference[Référence,window=_blank]](https://docs.github.com/en/free-pro-team@latest/actions/reference%5BR%C3%A9f%C3%A9rence,window=_blank%5D) renvoie maintenant sur la page d'accueil des actions au lieu des références. 

Il faudrait retrouver la page référencée pour corriger l'URL, mais je n'y suis pas parvenue de mon côté.

**Comment by dduportal** [comment]
Voici le nouveau lien: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions

**Comment by MarionPlt** [comment]
Traité dans la PR #26
